
create table exchange_registration
(
    id                                   serial not null
        constraint exchange_registration_pkey
            primary key,
    form_id                              text,
    registration_id                      text
        constraint exchange_registration_registration_id_key
            unique,
    submitted_at                         timestamp with time zone,
    first_name                           text,
    last_name                            text,
    organization                         text,
    title                                text,
    email                                text,
    phone                                text,
    registration_type                    text,
    small_business_number                text,
    current_nvp_supplier                 text,
    first_exchange_org                   text,
    first_exchange_person                text,
    address                              text,
    suite                                text,
    address_city                         text,
    address_state                        text,
    address_zip                          text,
    hear_about_exchange                  text,
    one_one                              text,
    time_zone                            text,
    profile                              text,
    headshot                             text,
    industries                           text,
    other_industries                     text,
    supplier_registration_fee            numeric,
    small_business_registration_fee      numeric,
    discount_code                        text,
    total_price                          numeric,
    payment_method                       text,
    name_on_card                         text,
    credit_card_info                     text,
    billing_address                      text,
    agreement                            text,
    registration_status                  text,
    created_at                           timestamp with time zone default now(),
    updated_at                           timestamp with time zone default now(),
    login_created                        boolean,
    supplier_registration_quantity       integer,
    small_business_registration_quantity integer,
    issue_resolution                     text,
    issue_notes                          text,
    approval_status                      text,
    check_received                       text,
    meetmax_id                           text,
    meetmax_status                       text,
    state_organization                   text,
    rollover                             boolean,
    meetings                             integer,
    thumbnail_image                      text,
    intrado_id                           text
);

